# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FXGraph

class DType(object):
    FLOAT32 = 0
    FLOAT64 = 1
    INT32 = 2
    INT64 = 3
    UINT8 = 4
    INT8 = 5
    BOOL = 6
    BFLOAT16 = 7
    FLOAT16 = 8
