# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FXGraph

class OpType(object):
    placeholder = 0
    get_attr = 1
    call_function = 2
    call_method = 3
    call_module = 4
    output = 5
