[package]
name = "teeny-http"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.teenygrad.org/api/teeny-http/"
keywords = ["http", "download", "fetch", "reqwest"]
categories = ["web-programming::http-client", "network-programming"]

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
reqwest.workspace = true
indicatif.workspace = true
