[package]
name = "teeny-http"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
reqwest.workspace = true
indicatif.workspace = true