[package]
name = "teeny-cache"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.teenygrad.org/api/teeny-cache/"
keywords = ["cache", "llm", "inference", "kv-cache"]
categories = ["caching", "science"]

[dependencies]
