#!/bin/sh

set -e

RELOGIN_REQUIRED=false

# install build tools
sudo apt-get install build-essential cmake ninja-build python3-dev

# checkif rustc is installed, if not install it
if ! command -v rustc &> /dev/null
thenz
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    . "$HOME/.cargo/env"

    cargo install cargo-expand
    cargo install cargo-watch

    RELOGIN_REQUIRED=true
else
    echo "Rust is installed, updating it"
    rustup update
fi


if [ "$RELOGIN_REQUIRED" = true ]; then
    echo "Please logout and login again, as new tools are installed"
    exit 0
fi
