/*
 * Copyright (c) 2026 Teenygrad.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! The Triton-like kernel DSL for [teenygrad](https://teenygrad.org). Kernel functions are
//! written against [`triton`]/[`triton_lang`]'s types and `#[kernel]`-annotated
//! (`teeny_macros::kernel`); [`triton_lang::TRITON`] embeds the DSL source as a string constant
//! (generated by `build.rs`), consumed by the custom `teenyc` compiler at kernel-compile time.
//! See the crate README for the runtime `teenyc`/`TEENYC_PATH` setup this implies.

// Kernel-DSL trait methods (e.g. `load`, `dot_scaled`) and combinator function-pointer types
// mirror Triton's own many-parameter, tensor-of-function-pointer signatures -- inherent to the
// domain, not something to refactor away.
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![warn(missing_docs)]

/// Error types.
pub mod error;
/// Host-side kernel I/O layout (`KernelIo` / `PtrRole`), derived from marked pointer params.
pub mod kernel_io;
/// The `Triton` DSL trait and its supporting types.
pub mod triton;
/// The generated DSL source text, embedded as [`triton_lang::TRITON`].
pub mod triton_lang;

pub use kernel_io::{
    BlockSized, KernelIo, KernelIoLayout, NElementsTiled, PointwiseFuseProbe,
    PointwiseFuseProbeExt, PtrRole,
};

/// A compiled kernel's identity: its name, type signature, and generated source block.
#[derive(Debug)]
pub struct TritonKernel {
    /// The kernel's name.
    pub name: &'static str,
    /// The kernel's type signature.
    pub sig: &'static str,
    /// The generated DSL source block for this kernel.
    pub block_str: &'static str,
}
