[package]
name = "teeny-data"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
reqwest.workspace = true
thiserror.workspace = true
ndarray.workspace = true
csv.workspace = true