[package]
name = "teeny-data"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.teenygrad.org/api/teeny-data/"
keywords = ["dataset", "safetensors", "machine-learning", "data-loading"]
categories = ["science", "filesystem"]

[dependencies]
teeny-core.workspace = true
tokio.workspace = true
reqwest.workspace = true
thiserror.workspace = true
anyhow.workspace = true
ndarray.workspace = true
csv.workspace = true
safetensors.workspace = true
memmap2.workspace = true
