[package]
name = "teeny-llm"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme.workspace = true

[[bin]]
name = "tllm"
path = "src/server/main.rs"

[[bin]]
name = "tllm-agent"
path = "src/agent/main.rs"

[[bin]]
name = "tllm-console"
path = "src/console/main.rs"

[dependencies]
