[package]
name = "teeny-llm"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tllm"
path = "src/server/main.rs"

[[bin]]
name = "tllm-agent"
path = "src/agent/main.rs"

[[bin]]
name = "tllm-console"
path = "src/console/main.rs"

[dependencies]
