[package]
name = "teeny-llm"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.teenygrad.org/api/teeny-llm/"
keywords = ["llm", "inference", "server", "openapi"]
categories = ["science", "command-line-utilities", "web-programming::http-server"]

[[bin]]
name = "teeny-llm"
path = "src/server/main.rs"

[dependencies]
