[package]
name = "teeny-jit"
version = "0.1.0"
edition = "2024"

[dependencies]
teeny-driver = { path = "../../drivers/teeny-driver" }
teeny-core = { path = "../../core/teeny-core" }
syn.workspace = true
proc-macro2.workspace = true
thiserror.workspace = true