[package]
name = "teeny-triton"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
teeny-core.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
dotenv.workspace = true
thiserror.workspace = true
anyhow.workspace = true
teeny-core.workspace = true
teeny-compiler.workspace = true
teeny-macros.workspace = true
teeny-cuda.workspace = true

[build-dependencies]
cargo_metadata.workspace = true
