[package]
name = "teeny-data"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
reqwest.workspace = true
flate2.workspace = true
half.workspace = true
# teenygrad dependencies
teeny-tensor.workspace = true