[package]
name = "teeny-nlp"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.teenygrad.org/api/teeny-nlp/"
keywords = ["nlp", "tokenizer", "text-processing", "regex"]
categories = ["text-processing", "science"]

[dependencies]
fancy-regex.workspace = true
rustc-hash.workspace = true
regex.workspace = true
bstr.workspace = true
serde.workspace = true