[package]
name = "teeny-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme.workspace = true

[features]
default = ["training"]
std = []
training = []

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
sha2.workspace = true