[package]
name = "teeny-core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.teenygrad.org/api/teeny-core/"
keywords = ["machine-learning", "tensor", "deep-learning", "no-std", "autograd"]
categories = ["science", "no-std", "algorithms"]

[features]
default = ["training"]
std = []
training = []

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
sha2.workspace = true