[package]
name = "teeny-core"
version = "0.1.0"
edition = "2024"

[features]
default = ["ndarray", "training"]
ndarray = ["dep:ndarray", "ndarray-rand"]
training = []

[dependencies]
ndarray = {workspace = true, optional = true}
ndarray-rand = {workspace = true, optional = true}
thiserror.workspace = true
once_cell.workspace = true
rand.workspace = true
derive_builder.workspace = true
uuid.workspace = true
half.workspace = true
num-traits.workspace = true
