[package]
name = "teeny-mnist"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
clap.workspace = true
reqwest.workspace = true
teeny-core = { path = "../../teeny-core/teeny-core" }