[package]
name = "teeny-torch"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme.workspace = true

[lib]
name = "teenygrad"
crate-type = ["cdylib"]

[dependencies]
teeny-core.workspace = true
teeny-fxgraph.workspace = true
teeny-compiler.workspace = true
thiserror.workspace = true
pyo3.workspace = true
flatbuffers.workspace = true
regex.workspace = true
egg.workspace = true

[dev-dependencies]
flate2.workspace = true

[build-dependencies]
flatc-rust.workspace = true
cargo_metadata.workspace = true
pyo3-build-config.workspace = true
