[package]
name = "teeny-cpu"
version = "0.1.0"
edition = "2024"

[dependencies]
teeny-core = { path = "../../core/teeny-core" }
teeny-driver = { path = "../teeny-driver" }
ctor.workspace = true
ndarray.workspace = true