[package]
name = "teeny-vision"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.teenygrad.org/api/teeny-vision/"
keywords = ["computer-vision", "machine-learning", "mnist", "images"]
categories = ["computer-vision", "science"]

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
teeny-core.workspace = true
parquet.workspace = true
arrow-array.workspace = true
image.workspace = true

[dev-dependencies]
tokio.workspace = true
reqwest.workspace = true
indicatif.workspace = true
dotenv.workspace = true
rand.workspace = true
teeny-kernels = { path = "../../kernels/teeny-kernels" }
teeny-cuda = { path = "../../drivers/teeny-cuda" }
teeny-compiler = { path = "../../compiler/teeny-compiler" }