[package]
name = "teeny-macros"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme = "README.md"
documentation = "https://docs.teenygrad.org/api/teeny-macros/"
keywords = ["macros", "proc-macro", "kernel", "codegen"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true

[dev-dependencies]
insta.workspace = true
quote.workspace = true
proc-macro2.workspace = true
trybuild = "1.0"

