/*
 * Copyright (c) 2026 teenygrad (https://teenygrad.org).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use std::path::Path;

/// Reads the assembly for the `compile_kernel`-produced artifact at `path` and returns it in the
/// form compile-only snapshot tests want.
///
/// `LlvmCompiler` writes the assembly next to the object file with a `.s` extension; an artifact
/// without one (e.g. cached by an older `LlvmCompiler`) is read from `path` itself, lossily
/// decoded as UTF-8 since a RISC-V object is an ELF binary. Two backend-specific quirks this
/// papers over so call sites don't have to:
/// - CUDA's assembly is PTX, and from its first `.file` debug directive onward it embeds an
///   absolute, environment-specific cache-dir path, followed by a DWARF `.debug_info` dump that
///   re-encodes that same path byte-by-byte -- roughly doubling the snapshot's size with content
///   that isn't the actual generated instructions and isn't portable across machines/CI with a
///   different `TEENYC_CACHE_DIR`. Truncating there keeps the snapshot to just the instructions.
/// - RISC-V's assembly declares its source file at the start of the function body, so the same
///   truncation would drop the code. The cache directory is replaced with `$TEENYC_CACHE_DIR`
///   instead, which keeps the snapshot portable.
pub fn read_compiled_asm(path: impl AsRef<Path>) -> String {
    let path = path.as_ref();
    let asm_path = path.with_extension("s");
    let source = if asm_path.exists() {
        asm_path.as_path()
    } else {
        path
    };
    let bytes = std::fs::read(source)
        .unwrap_or_else(|e| panic!("missing compiled artifact {source:?}: {e}"));
    let text = String::from_utf8_lossy(&bytes);

    if text.contains("Generated by LLVM NVPTX Back-End") {
        return text
            .split("\t.file\t1")
            .next()
            .unwrap_or(&text)
            .trim()
            .to_string();
    }

    match source.parent() {
        Some(cache_dir) if !cache_dir.as_os_str().is_empty() => text
            .replace(&*cache_dir.to_string_lossy(), "$TEENYC_CACHE_DIR")
            .trim()
            .to_string(),
        _ => text.trim().to_string(),
    }
}
