[package]
name = "teeny-kernels"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true
readme.workspace = true

[lib]

[features]
default = ["cuda", "training"]
cuda = ["dep:teeny-cuda"]
training = ["teeny-core/training"]

[dependencies]
thiserror.workspace = true
anyhow.workspace = true
teeny-macros = { path = "../../macros/teeny-macros", version = "0.1.0" }
teeny-core = { path = "../../core/teeny-core", version = "0.1.0" }
teeny-triton = { path = "../teeny-triton", version = "0.1.0" }
teeny-cuda = { path = "../../drivers/teeny-cuda", version = "0.1.0", optional = true }

[dev-dependencies]
teeny-compiler = { path = "../../compiler/teeny-compiler" }
dotenv.workspace = true
insta.workspace = true