/*
 * Copyright (c) 2026 teenygrad (https://teenygrad.org).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Nearest-neighbour 2-D upsample forward and backward tests.
//
// Kernel:  upsample_nearest2d_forward / upsample_nearest2d_backward
// Layout:  NCHW float32
//
// Dimensions:
//   B=2, C=4, H=4, W=4, SCALE_H=2, SCALE_W=2
//   OH = H * SCALE_H = 8,  OW = W * SCALE_W = 8
//
// Forward grid: B*C*OH * ceil(OW/BLOCK_OW) CTAs over output positions.
// Backward grid: B*C*H * ceil(W/BLOCK_IW) CTAs over input positions;
//   each CTA sums SCALE_H*SCALE_W upstream gradients — no atomic ops.
//
// Fixtures generated by tests/fixtures/upsample_nearest2d/generate.py.

use std::path::PathBuf;

use dotenv::dotenv;
use insta::assert_debug_snapshot;
#[cfg(feature = "hardware")]
use teeny_core::device::Device;
#[cfg(feature = "hardware")]
use teeny_core::device::buffer::Buffer;
use teeny_core::device::program::Kernel;

#[cfg(feature = "hardware")]
use teeny_test::load_fixture;

// ── Dimensions ────────────────────────────────────────────────────────────────

#[cfg(feature = "hardware")]
const B: usize = 2;
#[cfg(feature = "hardware")]
const C: usize = 4;
#[cfg(feature = "hardware")]
const H: usize = 4;
#[cfg(feature = "hardware")]
const W: usize = 4;
const SCALE_H: i32 = 2;
const SCALE_W: i32 = 2;
#[cfg(feature = "hardware")]
const OH: usize = H * SCALE_H as usize; // 8
#[cfg(feature = "hardware")]
const OW: usize = W * SCALE_W as usize; // 8
const BLOCK_OW: i32 = 4;

// ── Fixture loader ─────────────────────────────────────────────────────────────

// ── MLIR snapshot tests ───────────────────────────────────────────────────────

#[test]
fn test_upsample_nearest2d_forward_snapshot() -> anyhow::Result<()> {
    dotenv().ok();

    let kernel =
        teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dForward::<f32>::new(
            SCALE_H, SCALE_W, BLOCK_OW,
        );
    let target = teeny_runtime::reference_target();
    let ptx_path = PathBuf::from(teeny_runtime::compile_kernel(
        &kernel, &target, true, false,
    )?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;

    assert_debug_snapshot!(
        format!(
            "upsample_nearest2d_forward_source_{}",
            teeny_runtime::BACKEND_NAME
        ),
        kernel.source()
    );
    assert_debug_snapshot!(
        format!(
            "upsample_nearest2d_forward_mlir_{}",
            teeny_runtime::BACKEND_NAME
        ),
        mlir.trim()
    );

    Ok(())
}

#[test]
fn test_upsample_nearest2d_backward_snapshot() -> anyhow::Result<()> {
    dotenv().ok();

    let kernel =
        teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dBackward::<f32>::new(
            SCALE_H, SCALE_W, BLOCK_OW,
        );
    let target = teeny_runtime::reference_target();
    let ptx_path = PathBuf::from(teeny_runtime::compile_kernel(
        &kernel, &target, true, false,
    )?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;

    assert_debug_snapshot!(
        format!(
            "upsample_nearest2d_backward_source_{}",
            teeny_runtime::BACKEND_NAME
        ),
        kernel.source()
    );
    assert_debug_snapshot!(
        format!(
            "upsample_nearest2d_backward_mlir_{}",
            teeny_runtime::BACKEND_NAME
        ),
        mlir.trim()
    );

    Ok(())
}

// ── CUDA forward test ─────────────────────────────────────────────────────────

#[test]
#[cfg(feature = "hardware")]
fn test_upsample_nearest2d_forward_cuda() -> anyhow::Result<()> {
    dotenv().ok();
    let device = teeny_runtime::open()?;

    let x_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "upsample_nearest2d/x.bin");
    let expected = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "upsample_nearest2d/expected_forward.bin",
    );

    assert_eq!(x_host.len(), B * C * H * W);
    assert_eq!(expected.len(), B * C * OH * OW);

    let mut x_buf = device.buffer::<f32>(B * C * H * W)?;
    let y_buf = device.buffer::<f32>(B * C * OH * OW)?;
    x_buf.to_device(&x_host)?;

    let kernel =
        teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dForward::<f32>::new(
            SCALE_H, SCALE_W, BLOCK_OW,
        );
    let target = teeny_runtime::default_target(&device)?;
    let ptx_path = teeny_runtime::compile_kernel(&kernel, &target, true, false)?;
    let program = teeny_runtime::load_program::<
        teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dForward<f32>,
    >(&ptx_path)?;

    // Grid: B*C*OH * ceil(OW/BLOCK_OW)
    let num_ow_tiles = OW.div_ceil(BLOCK_OW as usize);
    let cfg = teeny_runtime::launch_config_custom(
        [(B * C * OH * num_ow_tiles) as u32, 1, 1],
        [128, 1, 1],
        [1, 1, 1],
    );

    device.launch(
        &program,
        &cfg,
        (
            x_buf.as_device_ptr(),
            y_buf.as_device_ptr(),
            B as i32,
            C as i32,
            H as i32,
            W as i32,
            OH as i32,
            OW as i32,
        ),
    )?;

    let mut y_host = vec![0.0f32; B * C * OH * OW];
    y_buf.to_host(&mut y_host)?;

    for i in 0..(B * C * OH * OW) {
        assert_eq!(
            y_host[i], expected[i],
            "upsample forward mismatch at {i}: got={} expected={}",
            y_host[i], expected[i],
        );
    }

    Ok(())
}

// ── CUDA backward test ────────────────────────────────────────────────────────

#[test]
#[cfg(feature = "hardware")]
fn test_upsample_nearest2d_backward_cuda() -> anyhow::Result<()> {
    dotenv().ok();
    let device = teeny_runtime::open()?;

    let dy_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "upsample_nearest2d/dy.bin");
    let expected = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "upsample_nearest2d/expected_backward.bin",
    );

    assert_eq!(dy_host.len(), B * C * OH * OW);
    assert_eq!(expected.len(), B * C * H * W);

    let mut dy_buf = device.buffer::<f32>(B * C * OH * OW)?;
    let dx_buf = device.buffer::<f32>(B * C * H * W)?;
    dy_buf.to_device(&dy_host)?;

    let kernel =
        teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dBackward::<f32>::new(
            SCALE_H, SCALE_W, BLOCK_OW,
        );
    let target = teeny_runtime::default_target(&device)?;
    let ptx_path = teeny_runtime::compile_kernel(&kernel, &target, true, false)?;
    let program = teeny_runtime::load_program::<
        teeny_kernels::nn::tensor::upsample_nearest2d::UpsampleNearest2dBackward<f32>,
    >(&ptx_path)?;

    // Grid: B*C*H * ceil(W/BLOCK_IW) — over input positions.
    let num_iw_tiles = W.div_ceil(BLOCK_OW as usize);
    let cfg = teeny_runtime::launch_config_custom(
        [(B * C * H * num_iw_tiles) as u32, 1, 1],
        [128, 1, 1],
        [1, 1, 1],
    );

    device.launch(
        &program,
        &cfg,
        (
            dy_buf.as_device_ptr(),
            dx_buf.as_device_ptr(),
            B as i32,
            C as i32,
            H as i32,
            W as i32,
            OH as i32,
            OW as i32,
        ),
    )?;

    let mut dx_host = vec![0.0f32; B * C * H * W];
    dx_buf.to_host(&mut dx_host)?;

    for i in 0..(B * C * H * W) {
        assert!(
            (dx_host[i] - expected[i]).abs() < 1e-5,
            "upsample backward mismatch at {i}: got={} expected={}",
            dx_host[i],
            expected[i],
        );
    }

    Ok(())
}
