/*
 * Copyright (c) 2026 teenygrad (https://teenygrad.org).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Flash Attention 2 forward and backward tests.
//
// Layout: [BH, N_CTX, HEAD_DIM] row-major, BH = BATCH * N_HEADS.
//
// Grid:  (N_CTX_Q or N_CTX_K, BH, 1) — one CTA per (batch_head, row).
// Block: (PTX_LAUNCH_THREADS_X, 1, 1) — Triton chooses 4 warps (128 threads).
//
// Fixtures generated by tests/fixtures/generate.py.

use std::path::PathBuf;

use dotenv::dotenv;
use insta::assert_debug_snapshot;
#[cfg(feature = "hardware")]
use teeny_core::device::Device;
#[cfg(feature = "hardware")]
use teeny_core::device::buffer::Buffer;
use teeny_core::device::program::Kernel;

#[cfg(feature = "hardware")]
use teeny_test::load_fixture;

// ── Dimensions ────────────────────────────────────────────────────────────────
#[cfg(feature = "hardware")]
const BH: usize = 4; // BATCH=2 * N_HEADS=2
#[cfg(feature = "hardware")]
const N_CTX: usize = 8;
const HEAD_DIM: i32 = 64;
#[cfg(feature = "hardware")]
const HEAD_DIM_U: usize = HEAD_DIM as usize;
#[cfg(feature = "hardware")]
const SOFTMAX_SCALE: f32 = 0.125; // 1 / sqrt(64)
// Triton compiles to 4 warps (128 threads) regardless of HEAD_DIM.
#[cfg(feature = "hardware")]
const PTX_LAUNCH_THREADS_X: u32 = 128;

#[cfg(feature = "hardware")]
const N_QKV: usize = BH * N_CTX * HEAD_DIM_U;
#[cfg(feature = "hardware")]
const N_L: usize = BH * N_CTX;

// ── Fixture loader ─────────────────────────────────────────────────────────────

// ── MLIR snapshot tests ───────────────────────────────────────────────────────

#[test]
fn test_flash_attention2_forward_snapshot() -> anyhow::Result<()> {
    dotenv().ok();

    let kernel =
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2Forward::<f32>::new(HEAD_DIM);
    let target = teeny_runtime::reference_target();
    let ptx_path = PathBuf::from(teeny_runtime::compile_kernel(
        &kernel, &target, true, false,
    )?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;

    assert_debug_snapshot!(
        format!(
            "flash_attention2_forward_source_{}",
            teeny_runtime::BACKEND_NAME
        ),
        kernel.source()
    );
    assert_debug_snapshot!(
        format!(
            "flash_attention2_forward_mlir_{}",
            teeny_runtime::BACKEND_NAME
        ),
        mlir.trim()
    );

    Ok(())
}

// ── CUDA integration test — forward ──────────────────────────────────────────

#[test]
#[cfg(feature = "hardware")]
fn test_flash_attention2_forward_cuda() -> anyhow::Result<()> {
    dotenv().ok();
    let device = teeny_runtime::open()?;

    let q_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/q.bin");
    let k_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/k.bin");
    let v_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/v.bin");
    let expected_o = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "flash_attn2/expected_forward_o.bin",
    );
    let expected_l = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "flash_attn2/expected_forward_l.bin",
    );

    assert_eq!(q_host.len(), N_QKV);
    assert_eq!(expected_o.len(), N_QKV);
    assert_eq!(expected_l.len(), N_L);

    let mut q_buf = device.buffer::<f32>(N_QKV)?;
    let mut k_buf = device.buffer::<f32>(N_QKV)?;
    let mut v_buf = device.buffer::<f32>(N_QKV)?;
    let o_buf = device.buffer::<f32>(N_QKV)?;
    let l_buf = device.buffer::<f32>(N_L)?;

    q_buf.to_device(&q_host)?;
    k_buf.to_device(&k_host)?;
    v_buf.to_device(&v_host)?;

    let kernel =
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2Forward::<f32>::new(HEAD_DIM);
    let target = teeny_runtime::default_target(&device)?;
    let ptx_path = teeny_runtime::compile_kernel(&kernel, &target, true, false)?;
    println!("[flash_attention2_forward] compiled PTX: {ptx_path}");

    let program = teeny_runtime::load_program::<
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2Forward<f32>,
    >(&ptx_path)?;

    let cfg = teeny_runtime::launch_config_custom(
        [N_CTX as u32, BH as u32, 1],
        [PTX_LAUNCH_THREADS_X, 1, 1],
        [1, 1, 1],
    );

    device.launch(
        &program,
        &cfg,
        (
            q_buf.as_device_ptr(),
            k_buf.as_device_ptr(),
            v_buf.as_device_ptr(),
            o_buf.as_device_ptr(),
            l_buf.as_device_ptr(),
            N_CTX as i32,
            N_CTX as i32,
            SOFTMAX_SCALE,
            f32::NEG_INFINITY,
        ),
    )?;

    let mut o_host = vec![0.0f32; N_QKV];
    let mut l_host = vec![0.0f32; N_L];
    o_buf.to_host(&mut o_host)?;
    l_buf.to_host(&mut l_host)?;

    for i in 0..N_QKV {
        assert!(
            (o_host[i] - expected_o[i]).abs() < 1e-4,
            "flash_attention2_forward O mismatch at {i}: gpu={}, expected={}",
            o_host[i],
            expected_o[i],
        );
    }

    for i in 0..N_L {
        assert!(
            (l_host[i] - expected_l[i]).abs() < 1e-4,
            "flash_attention2_forward L mismatch at {i}: gpu={}, expected={}",
            l_host[i],
            expected_l[i],
        );
    }

    Ok(())
}

// ── MLIR snapshot tests — backward ───────────────────────────────────────────

#[test]
fn test_flash_attention2_backward_dq_snapshot() -> anyhow::Result<()> {
    dotenv().ok();

    let kernel =
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDq::<f32>::new(HEAD_DIM);
    let target = teeny_runtime::reference_target();
    let ptx_path = PathBuf::from(teeny_runtime::compile_kernel(
        &kernel, &target, true, false,
    )?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;

    assert_debug_snapshot!(
        format!(
            "flash_attention2_backward_dq_source_{}",
            teeny_runtime::BACKEND_NAME
        ),
        kernel.source()
    );
    assert_debug_snapshot!(
        format!(
            "flash_attention2_backward_dq_mlir_{}",
            teeny_runtime::BACKEND_NAME
        ),
        mlir.trim()
    );

    Ok(())
}

#[test]
fn test_flash_attention2_backward_dkv_snapshot() -> anyhow::Result<()> {
    dotenv().ok();

    let kernel =
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDkv::<f32>::new(HEAD_DIM);
    let target = teeny_runtime::reference_target();
    let ptx_path = PathBuf::from(teeny_runtime::compile_kernel(
        &kernel, &target, true, false,
    )?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;

    assert_debug_snapshot!(
        format!(
            "flash_attention2_backward_dkv_source_{}",
            teeny_runtime::BACKEND_NAME
        ),
        kernel.source()
    );
    assert_debug_snapshot!(
        format!(
            "flash_attention2_backward_dkv_mlir_{}",
            teeny_runtime::BACKEND_NAME
        ),
        mlir.trim()
    );

    Ok(())
}

// ── CUDA integration test — backward dQ ──────────────────────────────────────

#[test]
#[cfg(feature = "hardware")]
fn test_flash_attention2_backward_dq_cuda() -> anyhow::Result<()> {
    dotenv().ok();
    let device = teeny_runtime::open()?;

    let q_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/q.bin");
    let k_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/k.bin");
    let v_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/v.bin");
    let o_host_f = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "flash_attn2/expected_forward_o.bin",
    );
    let l_host_f = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "flash_attn2/expected_forward_l.bin",
    );
    let do_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/do.bin");
    let expected_dq = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "flash_attn2/expected_backward_dq.bin",
    );

    let mut q_buf = device.buffer::<f32>(N_QKV)?;
    let mut k_buf = device.buffer::<f32>(N_QKV)?;
    let mut v_buf = device.buffer::<f32>(N_QKV)?;
    let mut o_buf = device.buffer::<f32>(N_QKV)?;
    let mut do_buf = device.buffer::<f32>(N_QKV)?;
    let mut l_buf = device.buffer::<f32>(N_L)?;
    let dq_buf = device.buffer::<f32>(N_QKV)?;

    q_buf.to_device(&q_host)?;
    k_buf.to_device(&k_host)?;
    v_buf.to_device(&v_host)?;
    o_buf.to_device(&o_host_f)?;
    do_buf.to_device(&do_host)?;
    l_buf.to_device(&l_host_f)?;

    let kernel =
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDq::<f32>::new(HEAD_DIM);
    let target = teeny_runtime::default_target(&device)?;
    let ptx_path = teeny_runtime::compile_kernel(&kernel, &target, true, false)?;
    println!("[flash_attention2_backward_dq] compiled PTX: {ptx_path}");

    let program = teeny_runtime::load_program::<
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDq<f32>,
    >(&ptx_path)?;

    let cfg = teeny_runtime::launch_config_custom(
        [N_CTX as u32, BH as u32, 1],
        [PTX_LAUNCH_THREADS_X, 1, 1],
        [1, 1, 1],
    );

    device.launch(
        &program,
        &cfg,
        (
            q_buf.as_device_ptr(),
            k_buf.as_device_ptr(),
            v_buf.as_device_ptr(),
            o_buf.as_device_ptr(),
            do_buf.as_device_ptr(),
            l_buf.as_device_ptr(),
            dq_buf.as_device_ptr(),
            N_CTX as i32,
            N_CTX as i32,
            SOFTMAX_SCALE,
        ),
    )?;

    let mut dq_host = vec![0.0f32; N_QKV];
    dq_buf.to_host(&mut dq_host)?;

    for i in 0..N_QKV {
        assert!(
            (dq_host[i] - expected_dq[i]).abs() < 1e-3,
            "flash_attention2_backward_dq mismatch at {i}: gpu={}, expected={}",
            dq_host[i],
            expected_dq[i],
        );
    }

    Ok(())
}

// ── CUDA integration test — backward dK / dV ─────────────────────────────────

#[test]
#[cfg(feature = "hardware")]
fn test_flash_attention2_backward_dkv_cuda() -> anyhow::Result<()> {
    dotenv().ok();
    let device = teeny_runtime::open()?;

    let q_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/q.bin");
    let k_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/k.bin");
    let v_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/v.bin");
    let o_host_f = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "flash_attn2/expected_forward_o.bin",
    );
    let l_host_f = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "flash_attn2/expected_forward_l.bin",
    );
    let do_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "flash_attn2/do.bin");
    let expected_dk = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "flash_attn2/expected_backward_dk.bin",
    );
    let expected_dv = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "flash_attn2/expected_backward_dv.bin",
    );

    let mut q_buf = device.buffer::<f32>(N_QKV)?;
    let mut k_buf = device.buffer::<f32>(N_QKV)?;
    let mut v_buf = device.buffer::<f32>(N_QKV)?;
    let mut o_buf = device.buffer::<f32>(N_QKV)?;
    let mut do_buf = device.buffer::<f32>(N_QKV)?;
    let mut l_buf = device.buffer::<f32>(N_L)?;
    let dk_buf = device.buffer::<f32>(N_QKV)?;
    let dv_buf = device.buffer::<f32>(N_QKV)?;

    q_buf.to_device(&q_host)?;
    k_buf.to_device(&k_host)?;
    v_buf.to_device(&v_host)?;
    o_buf.to_device(&o_host_f)?;
    do_buf.to_device(&do_host)?;
    l_buf.to_device(&l_host_f)?;

    let kernel =
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDkv::<f32>::new(HEAD_DIM);
    let target = teeny_runtime::default_target(&device)?;
    let ptx_path = teeny_runtime::compile_kernel(&kernel, &target, true, false)?;
    println!("[flash_attention2_backward_dkv] compiled PTX: {ptx_path}");

    let program = teeny_runtime::load_program::<
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDkv<f32>,
    >(&ptx_path)?;

    let cfg = teeny_runtime::launch_config_custom(
        [N_CTX as u32, BH as u32, 1],
        [PTX_LAUNCH_THREADS_X, 1, 1],
        [1, 1, 1],
    );

    device.launch(
        &program,
        &cfg,
        (
            q_buf.as_device_ptr(),
            k_buf.as_device_ptr(),
            v_buf.as_device_ptr(),
            o_buf.as_device_ptr(),
            do_buf.as_device_ptr(),
            l_buf.as_device_ptr(),
            dk_buf.as_device_ptr(),
            dv_buf.as_device_ptr(),
            N_CTX as i32,
            N_CTX as i32,
            SOFTMAX_SCALE,
        ),
    )?;

    let mut dk_host = vec![0.0f32; N_QKV];
    let mut dv_host = vec![0.0f32; N_QKV];
    dk_buf.to_host(&mut dk_host)?;
    dv_buf.to_host(&mut dv_host)?;

    for i in 0..N_QKV {
        assert!(
            (dk_host[i] - expected_dk[i]).abs() < 1e-3,
            "flash_attention2_backward_dkv dK mismatch at {i}: gpu={}, expected={}",
            dk_host[i],
            expected_dk[i],
        );
    }

    for i in 0..N_QKV {
        assert!(
            (dv_host[i] - expected_dv[i]).abs() < 1e-3,
            "flash_attention2_backward_dkv dV mismatch at {i}: gpu={}, expected={}",
            dv_host[i],
            expected_dv[i],
        );
    }

    Ok(())
}
