/*
 * Copyright (c) 2026 teenygrad (https://teenygrad.org).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// ElemwiseAdd forward and backward tests.
//
// Forward:  out[i] = a[i] + b[i]
// Backward: grad_a[i] = dy[i],  grad_b[i] = dy[i]
//
// Fixtures generated by tests/fixtures/elemwise_add/generate.py.

use dotenv::dotenv;
use insta::assert_debug_snapshot;
use std::path::PathBuf;
#[cfg(feature = "hardware")]
use teeny_core::device::Device;
#[cfg(feature = "hardware")]
use teeny_core::device::buffer::Buffer;
use teeny_core::device::program::Kernel;

#[cfg(feature = "hardware")]
const N: usize = 1024;
const BLOCK_SIZE: i32 = 128;

#[cfg(feature = "hardware")]
fn load(rel: &str) -> Vec<f32> {
    let path = format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), rel);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("missing {path}: {e}"));
    bytes
        .as_chunks::<4>()
        .0
        .iter()
        .map(|b| f32::from_le_bytes(*b))
        .collect()
}

// ── MLIR snapshot tests ───────────────────────────────────────────────────────

#[test]
fn test_elemwise_add_forward_snapshot() -> std::result::Result<(), Box<dyn std::error::Error>> {
    dotenv().ok();
    let kernel =
        teeny_kernels::nn::tensor::elemwise_add::ElemwiseAddForward::<f32>::new(BLOCK_SIZE);
    let target = teeny_runtime::reference_target();
    let ptx_path = PathBuf::from(teeny_runtime::compile_kernel(
        &kernel, &target, true, false,
    )?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;
    assert_debug_snapshot!(
        format!(
            "elemwise_add_forward_source_{}",
            teeny_runtime::BACKEND_NAME
        ),
        kernel.source()
    );
    assert_debug_snapshot!(
        format!("elemwise_add_forward_mlir_{}", teeny_runtime::BACKEND_NAME),
        mlir.trim()
    );
    Ok(())
}

#[test]
fn test_elemwise_add_backward_snapshot() -> std::result::Result<(), Box<dyn std::error::Error>> {
    dotenv().ok();
    let kernel =
        teeny_kernels::nn::tensor::elemwise_add::ElemwiseAddBackward::<f32>::new(BLOCK_SIZE);
    let target = teeny_runtime::reference_target();
    let ptx_path = PathBuf::from(teeny_runtime::compile_kernel(
        &kernel, &target, true, false,
    )?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;
    assert_debug_snapshot!(
        format!(
            "elemwise_add_backward_source_{}",
            teeny_runtime::BACKEND_NAME
        ),
        kernel.source()
    );
    assert_debug_snapshot!(
        format!("elemwise_add_backward_mlir_{}", teeny_runtime::BACKEND_NAME),
        mlir.trim()
    );
    Ok(())
}

// ── CUDA integration tests ────────────────────────────────────────────────────

#[test]
#[cfg(feature = "hardware")]
fn test_elemwise_add_forward_cuda() -> anyhow::Result<()> {
    dotenv().ok();
    let device = teeny_runtime::open()?;

    let a_host = load("elemwise_add/a.bin");
    let b_host = load("elemwise_add/b.bin");
    let expected = load("elemwise_add/expected_fwd.bin");

    assert_eq!(a_host.len(), N);
    assert_eq!(b_host.len(), N);
    assert_eq!(expected.len(), N);

    let mut a_buf = device.buffer::<f32>(N)?;
    let mut b_buf = device.buffer::<f32>(N)?;
    let out_buf = device.buffer::<f32>(N)?;

    a_buf.to_device(&a_host)?;
    b_buf.to_device(&b_host)?;

    let kernel =
        teeny_kernels::nn::tensor::elemwise_add::ElemwiseAddForward::<f32>::new(BLOCK_SIZE);
    let target = teeny_runtime::default_target(&device)?;
    let ptx_path = teeny_runtime::compile_kernel(&kernel, &target, true, false)?;
    let program = teeny_runtime::load_program::<
        teeny_kernels::nn::tensor::elemwise_add::ElemwiseAddForward<f32>,
    >(&ptx_path)?;

    let cfg = teeny_runtime::launch_config(N, &program);
    device.launch(
        &program,
        &cfg,
        (
            a_buf.as_device_ptr(),
            b_buf.as_device_ptr(),
            out_buf.as_device_ptr(),
            N as i32,
        ),
    )?;

    let mut out_host = vec![0.0f32; N];
    out_buf.to_host(&mut out_host)?;

    for i in 0..N {
        assert!(
            (out_host[i] - expected[i]).abs() < 1e-5,
            "forward mismatch at {i}: gpu={} expected={}",
            out_host[i],
            expected[i]
        );
    }
    Ok(())
}

#[test]
#[cfg(feature = "hardware")]
fn test_elemwise_add_backward_cuda() -> anyhow::Result<()> {
    dotenv().ok();
    let device = teeny_runtime::open()?;

    let dy_host = load("elemwise_add/dy.bin");
    let expected_ga = load("elemwise_add/expected_ga.bin");
    let expected_gb = load("elemwise_add/expected_gb.bin");

    assert_eq!(dy_host.len(), N);
    assert_eq!(expected_ga.len(), N);
    assert_eq!(expected_gb.len(), N);

    let mut dy_buf = device.buffer::<f32>(N)?;
    let grad_a_buf = device.buffer::<f32>(N)?;
    let grad_b_buf = device.buffer::<f32>(N)?;

    dy_buf.to_device(&dy_host)?;

    let kernel =
        teeny_kernels::nn::tensor::elemwise_add::ElemwiseAddBackward::<f32>::new(BLOCK_SIZE);
    let target = teeny_runtime::default_target(&device)?;
    let ptx_path = teeny_runtime::compile_kernel(&kernel, &target, true, false)?;
    let program = teeny_runtime::load_program::<
        teeny_kernels::nn::tensor::elemwise_add::ElemwiseAddBackward<f32>,
    >(&ptx_path)?;

    let cfg = teeny_runtime::launch_config(N, &program);
    device.launch(
        &program,
        &cfg,
        (
            dy_buf.as_device_ptr(),
            grad_a_buf.as_device_ptr(),
            grad_b_buf.as_device_ptr(),
            N as i32,
        ),
    )?;

    let mut ga_host = vec![0.0f32; N];
    let mut gb_host = vec![0.0f32; N];
    grad_a_buf.to_host(&mut ga_host)?;
    grad_b_buf.to_host(&mut gb_host)?;

    for i in 0..N {
        assert!(
            (ga_host[i] - expected_ga[i]).abs() < 1e-6,
            "grad_a mismatch at {i}: gpu={} expected={}",
            ga_host[i],
            expected_ga[i]
        );
        assert!(
            (gb_host[i] - expected_gb[i]).abs() < 1e-6,
            "grad_b mismatch at {i}: gpu={} expected={}",
            gb_host[i],
            expected_gb[i]
        );
    }
    Ok(())
}
