// Copyright 2025 Teenygrad contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Numerics for `conv2d_bn_silu_forward` (teenygrad-3dp5).
//!
//! This kernel had NO test of any kind -- no test file, no fixtures, no
//! snapshots, only a `tile_spec()` assertion in `graph/mod.rs`. Asserting a
//! generated spec does not exercise codegen, which is how three bugs lived in
//! teenygrad-1nr.18.5's prelude path, so the kernel could not be converted to
//! the Tile ABI with any confidence until this existed.
//!
//! The reference is PyTorch's `silu(scale * conv2d(x, w) + shift)`, generated by
//! `fixtures/generate.py`.

#![cfg(feature = "hardware")]

use dotenv::dotenv;
use teeny_core::device::Device;
use teeny_core::device::buffer::Buffer;
use teeny_kernels::nn::fused::conv2d_bn_silu::Conv2dBnSiluForward;
use teeny_test::load_fixture;

const NB: usize = 1;
const C_IN: usize = 4;
const C_OUT: usize = 4;
const HH: usize = 8;
const WW: usize = 8;
const KH: i32 = 3;
const KW: i32 = 3;
const STRIDE_H: i32 = 1;
const STRIDE_W: i32 = 1;
const PAD_H: i32 = 1;
const PAD_W: i32 = 1;
const G: i32 = 1;
const BLOCK_OW: i32 = 8;

// stride 1 with padding 1 and a 3-wide kernel keeps the spatial dims.
const OH: usize = HH;
const OW: usize = WW;

const PTX_LAUNCH_THREADS_X: u32 = 128;

#[test]
fn test_conv2d_bn_silu_forward_matches_reference() -> anyhow::Result<()> {
    dotenv().ok();
    let device = teeny_runtime::open()?;

    let x_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "conv2d_bn_silu/x.bin");
    let w_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "conv2d_bn_silu/w.bin");
    let scale_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "conv2d_bn_silu/bn_scale.bin");
    let shift_host = load_fixture(env!("CARGO_MANIFEST_DIR"), "conv2d_bn_silu/bn_shift.bin");
    let expected = load_fixture(
        env!("CARGO_MANIFEST_DIR"),
        "conv2d_bn_silu/expected_forward.bin",
    );

    assert_eq!(x_host.len(), NB * C_IN * HH * WW);
    assert_eq!(expected.len(), NB * C_OUT * OH * OW);

    let mut x_buf = device.buffer::<f32>(NB * C_IN * HH * WW)?;
    let mut w_buf = device.buffer::<f32>(C_OUT * C_IN * KH as usize * KW as usize)?;
    let mut s_buf = device.buffer::<f32>(C_OUT)?;
    let mut sh_buf = device.buffer::<f32>(C_OUT)?;
    let y_buf = device.buffer::<f32>(NB * C_OUT * OH * OW)?;

    x_buf.to_device(&x_host)?;
    w_buf.to_device(&w_host)?;
    s_buf.to_device(&scale_host)?;
    sh_buf.to_device(&shift_host)?;

    let kernel = Conv2dBnSiluForward::new(
        KH, KW, STRIDE_H, STRIDE_W, PAD_H, PAD_W, G, BLOCK_OW,
    );
    let target = teeny_runtime::default_target(&device)?;
    let ptx_path = teeny_runtime::compile_kernel(&kernel, &target, true, false)?;
    let program = teeny_runtime::load_program::<Conv2dBnSiluForward>(&ptx_path)?;

    let num_ow_tiles = OW.div_ceil(BLOCK_OW as usize);
    let grid_x = (NB * C_OUT * OH * num_ow_tiles) as u32;
    let cfg = teeny_runtime::launch_config_custom(
        [grid_x, 1, 1],
        [PTX_LAUNCH_THREADS_X, 1, 1],
        [1, 1, 1],
    );

    device.launch(
        &program,
        &cfg,
        (
            x_buf.as_device_ptr(),
            w_buf.as_device_ptr(),
            s_buf.as_device_ptr(),
            sh_buf.as_device_ptr(),
            y_buf.as_device_ptr(),
            NB as i32,
            C_IN as i32,
            C_OUT as i32,
            HH as i32,
            WW as i32,
            OH as i32,
            OW as i32,
        ),
    )?;

    let mut y_host = vec![0.0f32; NB * C_OUT * OH * OW];
    y_buf.to_host(&mut y_host)?;

    for i in 0..(NB * C_OUT * OH * OW) {
        assert!(
            (y_host[i] - expected[i]).abs() < 1e-3,
            "conv2d_bn_silu_forward mismatch at {i}: gpu={}, expected={}",
            y_host[i],
            expected[i]
        );
    }
    Ok(())
}
