/*
 * Copyright (c) 2026 Teenygrad.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Flash Attention 2 forward and backward tests.
//
// Layout: [BH, N_CTX, HEAD_DIM] row-major, BH = BATCH * N_HEADS.
//
// Grid:  (N_CTX_Q or N_CTX_K, BH, 1) — one CTA per (batch_head, row).
// Block: (PTX_LAUNCH_THREADS_X, 1, 1) — Triton chooses 4 warps (128 threads).
//
// Fixtures generated by tests/fixtures/generate.py.

use std::path::PathBuf;

use dotenv::dotenv;
use insta::assert_debug_snapshot;
use teeny_compiler::compiler::{driver::cuda::compile_kernel, target::cuda::Target};
use teeny_core::device::Device;
use teeny_core::device::buffer::Buffer;
use teeny_core::device::program::Kernel;

#[cfg(feature = "cuda")]
use teeny_cuda::{compiler::target::Capability, device::CudaLaunchConfig, errors::Result, testing};

// ── Dimensions ────────────────────────────────────────────────────────────────
const BH:       usize = 4;    // BATCH=2 * N_HEADS=2
const N_CTX:    usize = 8;
const HEAD_DIM: i32   = 64;
const HEAD_DIM_U: usize = HEAD_DIM as usize;
const SOFTMAX_SCALE: f32 = 0.125; // 1 / sqrt(64)
// Triton compiles to 4 warps (128 threads) regardless of HEAD_DIM.
const PTX_LAUNCH_THREADS_X: u32 = 128;

const N_QKV: usize = BH * N_CTX * HEAD_DIM_U;
const N_L:   usize = BH * N_CTX;

// ── Fixture loader ─────────────────────────────────────────────────────────────

fn load_fixture(rel: &str) -> Vec<f32> {
    let path = format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), rel);
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("missing fixture {path}: {e}"));
    bytes
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect()
}

// ── MLIR snapshot tests ───────────────────────────────────────────────────────

#[test]
fn test_flash_attention2_forward_snapshot() -> Result<()> {
    dotenv().ok();

    let kernel = teeny_kernels::nn::attention::flash_attn2::FlashAttention2Forward::new(HEAD_DIM);
    let target = Target::new(Capability::Sm90);
    let ptx_path = PathBuf::from(compile_kernel(&kernel, &target, true)?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;

    assert_debug_snapshot!("flash_attention2_forward_source", kernel.source());
    assert_debug_snapshot!("flash_attention2_forward_mlir",   mlir.trim());

    Ok(())
}

// ── CUDA integration test — forward ──────────────────────────────────────────

#[test]
#[cfg(feature = "cuda")]
fn test_flash_attention2_forward_cuda() -> Result<()> {
    dotenv().ok();
    let env = testing::setup_cuda_env()?;
    let device = env.device;

    let q_host      = load_fixture("flash_attn2/q.bin");
    let k_host      = load_fixture("flash_attn2/k.bin");
    let v_host      = load_fixture("flash_attn2/v.bin");
    let expected_o  = load_fixture("flash_attn2/expected_forward_o.bin");
    let expected_l  = load_fixture("flash_attn2/expected_forward_l.bin");

    assert_eq!(q_host.len(), N_QKV);
    assert_eq!(expected_o.len(), N_QKV);
    assert_eq!(expected_l.len(), N_L);

    let mut q_buf = device.buffer::<f32>(N_QKV)?;
    let mut k_buf = device.buffer::<f32>(N_QKV)?;
    let mut v_buf = device.buffer::<f32>(N_QKV)?;
    let o_buf     = device.buffer::<f32>(N_QKV)?;
    let l_buf     = device.buffer::<f32>(N_L)?;

    q_buf.to_device(&q_host)?;
    k_buf.to_device(&k_host)?;
    v_buf.to_device(&v_host)?;

    let kernel = teeny_kernels::nn::attention::flash_attn2::FlashAttention2Forward::new(HEAD_DIM);
    let target = Target::new(env.capability);
    let ptx_path = compile_kernel(&kernel, &target, true)?;
    println!("[flash_attention2_forward] compiled PTX: {ptx_path}");
    let ptx = std::fs::read(&ptx_path)?;

    let program = testing::load_program_from_ptx::<
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2Forward,
    >(&ptx)?;

    let cfg = CudaLaunchConfig {
        grid:    [N_CTX as u32, BH as u32, 1],
        block:   [PTX_LAUNCH_THREADS_X, 1, 1],
        cluster: [1, 1, 1],
    };

    device.launch(&program, &cfg, (
        q_buf.as_device_ptr() as *mut f32,
        k_buf.as_device_ptr() as *mut f32,
        v_buf.as_device_ptr() as *mut f32,
        o_buf.as_device_ptr() as *mut f32,
        l_buf.as_device_ptr() as *mut f32,
        N_CTX as i32,
        N_CTX as i32,
        SOFTMAX_SCALE,
        f32::NEG_INFINITY,
    ))?;

    let mut o_host = vec![0.0f32; N_QKV];
    let mut l_host = vec![0.0f32; N_L];
    o_buf.to_host(&mut o_host)?;
    l_buf.to_host(&mut l_host)?;

    for i in 0..N_QKV {
        assert!(
            (o_host[i] - expected_o[i]).abs() < 1e-4,
            "flash_attention2_forward O mismatch at {i}: gpu={}, expected={}",
            o_host[i], expected_o[i],
        );
    }

    for i in 0..N_L {
        assert!(
            (l_host[i] - expected_l[i]).abs() < 1e-4,
            "flash_attention2_forward L mismatch at {i}: gpu={}, expected={}",
            l_host[i], expected_l[i],
        );
    }

    Ok(())
}

// ── MLIR snapshot tests — backward ───────────────────────────────────────────

#[test]
fn test_flash_attention2_backward_dq_snapshot() -> Result<()> {
    dotenv().ok();

    let kernel = teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDq::new(HEAD_DIM);
    let target = Target::new(Capability::Sm90);
    let ptx_path = PathBuf::from(compile_kernel(&kernel, &target, true)?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;

    assert_debug_snapshot!("flash_attention2_backward_dq_source", kernel.source());
    assert_debug_snapshot!("flash_attention2_backward_dq_mlir",   mlir.trim());

    Ok(())
}

#[test]
fn test_flash_attention2_backward_dkv_snapshot() -> Result<()> {
    dotenv().ok();

    let kernel = teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDkv::new(HEAD_DIM);
    let target = Target::new(Capability::Sm90);
    let ptx_path = PathBuf::from(compile_kernel(&kernel, &target, true)?);
    let mlir = std::fs::read_to_string(ptx_path.with_extension("mlir"))?;

    assert_debug_snapshot!("flash_attention2_backward_dkv_source", kernel.source());
    assert_debug_snapshot!("flash_attention2_backward_dkv_mlir",   mlir.trim());

    Ok(())
}

// ── CUDA integration test — backward dQ ──────────────────────────────────────

#[test]
#[cfg(feature = "cuda")]
fn test_flash_attention2_backward_dq_cuda() -> Result<()> {
    dotenv().ok();
    let env = testing::setup_cuda_env()?;
    let device = env.device;

    let q_host   = load_fixture("flash_attn2/q.bin");
    let k_host   = load_fixture("flash_attn2/k.bin");
    let v_host   = load_fixture("flash_attn2/v.bin");
    let o_host_f = load_fixture("flash_attn2/expected_forward_o.bin");
    let l_host_f = load_fixture("flash_attn2/expected_forward_l.bin");
    let do_host  = load_fixture("flash_attn2/do.bin");
    let expected_dq = load_fixture("flash_attn2/expected_backward_dq.bin");

    let mut q_buf  = device.buffer::<f32>(N_QKV)?;
    let mut k_buf  = device.buffer::<f32>(N_QKV)?;
    let mut v_buf  = device.buffer::<f32>(N_QKV)?;
    let mut o_buf  = device.buffer::<f32>(N_QKV)?;
    let mut do_buf = device.buffer::<f32>(N_QKV)?;
    let mut l_buf  = device.buffer::<f32>(N_L)?;
    let dq_buf     = device.buffer::<f32>(N_QKV)?;

    q_buf.to_device(&q_host)?;
    k_buf.to_device(&k_host)?;
    v_buf.to_device(&v_host)?;
    o_buf.to_device(&o_host_f)?;
    do_buf.to_device(&do_host)?;
    l_buf.to_device(&l_host_f)?;

    let kernel = teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDq::new(HEAD_DIM);
    let target = Target::new(env.capability);
    let ptx_path = compile_kernel(&kernel, &target, true)?;
    println!("[flash_attention2_backward_dq] compiled PTX: {ptx_path}");
    let ptx = std::fs::read(&ptx_path)?;

    let program = testing::load_program_from_ptx::<
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDq,
    >(&ptx)?;

    let cfg = CudaLaunchConfig {
        grid:    [N_CTX as u32, BH as u32, 1],
        block:   [PTX_LAUNCH_THREADS_X, 1, 1],
        cluster: [1, 1, 1],
    };

    device.launch(&program, &cfg, (
        q_buf.as_device_ptr() as *mut f32,
        k_buf.as_device_ptr() as *mut f32,
        v_buf.as_device_ptr() as *mut f32,
        o_buf.as_device_ptr() as *mut f32,
        do_buf.as_device_ptr() as *mut f32,
        l_buf.as_device_ptr() as *mut f32,
        dq_buf.as_device_ptr() as *mut f32,
        N_CTX as i32,
        N_CTX as i32,
        SOFTMAX_SCALE,
    ))?;

    let mut dq_host = vec![0.0f32; N_QKV];
    dq_buf.to_host(&mut dq_host)?;

    for i in 0..N_QKV {
        assert!(
            (dq_host[i] - expected_dq[i]).abs() < 1e-3,
            "flash_attention2_backward_dq mismatch at {i}: gpu={}, expected={}",
            dq_host[i], expected_dq[i],
        );
    }

    Ok(())
}

// ── CUDA integration test — backward dK / dV ─────────────────────────────────

#[test]
#[cfg(feature = "cuda")]
fn test_flash_attention2_backward_dkv_cuda() -> Result<()> {
    dotenv().ok();
    let env = testing::setup_cuda_env()?;
    let device = env.device;

    let q_host   = load_fixture("flash_attn2/q.bin");
    let k_host   = load_fixture("flash_attn2/k.bin");
    let v_host   = load_fixture("flash_attn2/v.bin");
    let o_host_f = load_fixture("flash_attn2/expected_forward_o.bin");
    let l_host_f = load_fixture("flash_attn2/expected_forward_l.bin");
    let do_host  = load_fixture("flash_attn2/do.bin");
    let expected_dk = load_fixture("flash_attn2/expected_backward_dk.bin");
    let expected_dv = load_fixture("flash_attn2/expected_backward_dv.bin");

    let mut q_buf  = device.buffer::<f32>(N_QKV)?;
    let mut k_buf  = device.buffer::<f32>(N_QKV)?;
    let mut v_buf  = device.buffer::<f32>(N_QKV)?;
    let mut o_buf  = device.buffer::<f32>(N_QKV)?;
    let mut do_buf = device.buffer::<f32>(N_QKV)?;
    let mut l_buf  = device.buffer::<f32>(N_L)?;
    let dk_buf     = device.buffer::<f32>(N_QKV)?;
    let dv_buf     = device.buffer::<f32>(N_QKV)?;

    q_buf.to_device(&q_host)?;
    k_buf.to_device(&k_host)?;
    v_buf.to_device(&v_host)?;
    o_buf.to_device(&o_host_f)?;
    do_buf.to_device(&do_host)?;
    l_buf.to_device(&l_host_f)?;

    let kernel = teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDkv::new(HEAD_DIM);
    let target = Target::new(env.capability);
    let ptx_path = compile_kernel(&kernel, &target, true)?;
    println!("[flash_attention2_backward_dkv] compiled PTX: {ptx_path}");
    let ptx = std::fs::read(&ptx_path)?;

    let program = testing::load_program_from_ptx::<
        teeny_kernels::nn::attention::flash_attn2::FlashAttention2BackwardDkv,
    >(&ptx)?;

    let cfg = CudaLaunchConfig {
        grid:    [N_CTX as u32, BH as u32, 1],
        block:   [PTX_LAUNCH_THREADS_X, 1, 1],
        cluster: [1, 1, 1],
    };

    device.launch(&program, &cfg, (
        q_buf.as_device_ptr() as *mut f32,
        k_buf.as_device_ptr() as *mut f32,
        v_buf.as_device_ptr() as *mut f32,
        o_buf.as_device_ptr() as *mut f32,
        do_buf.as_device_ptr() as *mut f32,
        l_buf.as_device_ptr() as *mut f32,
        dk_buf.as_device_ptr() as *mut f32,
        dv_buf.as_device_ptr() as *mut f32,
        N_CTX as i32,
        N_CTX as i32,
        SOFTMAX_SCALE,
    ))?;

    let mut dk_host = vec![0.0f32; N_QKV];
    let mut dv_host = vec![0.0f32; N_QKV];
    dk_buf.to_host(&mut dk_host)?;
    dv_buf.to_host(&mut dv_host)?;

    for i in 0..N_QKV {
        assert!(
            (dk_host[i] - expected_dk[i]).abs() < 1e-3,
            "flash_attention2_backward_dkv dK mismatch at {i}: gpu={}, expected={}",
            dk_host[i], expected_dk[i],
        );
    }

    for i in 0..N_QKV {
        assert!(
            (dv_host[i] - expected_dv[i]).abs() < 1e-3,
            "flash_attention2_backward_dkv dV mismatch at {i}: gpu={}, expected={}",
            dv_host[i], expected_dv[i],
        );
    }

    Ok(())
}
